// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/namaa/AIAgent.tsx": () => import("../components/mockups/namaa/AIAgent.tsx"),
  "./components/mockups/namaa/Cards.tsx": () => import("../components/mockups/namaa/Cards.tsx"),
  "./components/mockups/namaa/Dashboard.tsx": () => import("../components/mockups/namaa/Dashboard.tsx"),
  "./components/mockups/namaa/FinancialHealth.tsx": () => import("../components/mockups/namaa/FinancialHealth.tsx"),
  "./components/mockups/namaa/Financing.tsx": () => import("../components/mockups/namaa/Financing.tsx"),
  "./components/mockups/namaa/Investments.tsx": () => import("../components/mockups/namaa/Investments.tsx"),
  "./components/mockups/namaa/Recommendation.tsx": () => import("../components/mockups/namaa/Recommendation.tsx"),
  "./components/mockups/namaa/Reports.tsx": () => import("../components/mockups/namaa/Reports.tsx"),
  "./components/mockups/namaa/Settings.tsx": () => import("../components/mockups/namaa/Settings.tsx")
};
